export const contactLang: Record<string, { [key: string]: string }> = {
  en: {
    title: "Get in Touch",
    contactInfo: "Contact Information",
    phone: "Phone",
    email: "Email",
    address: "Address",
    officeHours: "Office Hours",
    weekdays: "Monday - Friday: 9:00 AM - 6:00 PM",
    saturday: "Saturday: 10:00 AM - 4:00 PM",
    sunday: "Sunday: Closed",
    connectWithUs: "Connect With Us",
    socialMedia: "Follow us on social media for the latest updates and insights:",
    name: "Name",
    nameRequired: "Name is required",
    emailRequired: "Email is required",
    emailInvalid: "Invalid email address",
    message: "Message",
    messageRequired: "Message is required",
    send: "Send Message",
    sending: "Sending...",
    thankYou: "Thank you for your message. We'll get back to you soon!",
  },
  id: {
    title: "Hubungi Kami",
    contactInfo: "Informasi Kontak",
    phone: "Telepon",
    email: "Email",
    address: "Alamat",
    officeHours: "Jam Kerja",
    weekdays: "Senin - Jumat: 9:00 - 18:00",
    saturday: "Sabtu: 10:00 - 16:00",
    sunday: "Minggu: Tutup",
    connectWithUs: "Terhubung Dengan Kami",
    socialMedia: "Ikuti kami di media sosial untuk pembaruan dan wawasan terbaru:",
    name: "Nama",
    nameRequired: "Nama wajib diisi",
    emailRequired: "Email wajib diisi",
    emailInvalid: "Alamat email tidak valid",
    message: "Pesan",
    messageRequired: "Pesan wajib diisi",
    send: "Kirim Pesan",
    sending: "Mengirim...",
    thankYou: "Terima kasih atas pesan Anda. Kami akan segera menghubungi Anda!",
  },
}

